# Generated by Django 3.0.6 on 2020-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(max_length=2083, upload_to=''),
        ),
    ]
